# Generated by Django 5.0.6 on 2024-05-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=30, verbose_name='Студент/препод/гость')),
                ('login', models.CharField(max_length=30, verbose_name='login')),
                ('pasw', models.TextField(verbose_name='pasw')),
                ('code', models.TextField(default='', verbose_name='code')),
            ],
        ),
    ]
