# Generated by Django 5.0.6 on 2024-05-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_enterpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpass',
            name='password',
            field=models.CharField(default='-', max_length=30, verbose_name='login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterpass',
            name='user_type',
            field=models.CharField(default='-', max_length=30, verbose_name='Студент/препод/гость'),
            preserve_default=False,
        ),
    ]
