# Generated by Django 5.0.6 on 2024-05-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_enterpass_password_enterpass_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpass',
            name='id',
        ),
        migrations.AlterField(
            model_name='enterpass',
            name='password',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Enter password'),
        ),
    ]
