# Generated by Django 5.0.6 on 2024-05-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='ID решения')),
                ('resolve_date', models.CharField(max_length=100, verbose_name='Дата и время')),
                ('resolve_language', models.CharField(max_length=30, verbose_name='Язык')),
                ('task_id', models.CharField(max_length=50, verbose_name='ID задачи')),
                ('resolve', models.TextField(verbose_name='Файл с решением')),
                ('decision_status', models.CharField(max_length=30, verbose_name='Статус решения (верно/неверно)')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='ID решения')),
                ('title', models.CharField(max_length=50, verbose_name='Описание')),
                ('name', models.CharField(max_length=50, verbose_name='Имя задачи')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, verbose_name='ID решения')),
                ('task_id', models.CharField(max_length=30, verbose_name='Id задачи')),
                ('resolve', models.TextField(verbose_name='Файл с тестом')),
            ],
        ),
    ]
