# Generated by Django 5.0.6 on 2024-05-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_user_id_alter_resolve_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(default='-', max_length=50, verbose_name='id задачи'),
            preserve_default=False,
        ),
    ]
